try {
    console.log("hello") //it run
   console.log(a)//it throw error
} catch (error) {
    console.log("handle")
    
}finally{
    console.log("finall")
}

console.log("end")